### ISSUE TITLE
Resource punkt not found.

### ISSUE THREAD

**Issue by yangboz** [luisroque/large_laguage_models#4]
during  pip install -r requirements.txt 
it throws :

```
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle
```

and any idea dockerize them to image in Dockerfile?

**Comment by yangboz** [comment]
or if it is possible to replace NLTK module with SpacY,orther NLP module to avoid NLTK pains ?

**Comment by yangboz** [comment]
https://python.langchain.com/docs/modules/data_connection/document_transformers/text_splitters/split_by_token#spacy

NLTK issues: https://stackoverflow.com/questions/49546253/attributeerror-module-nltk-has-no-attribute-download

**Comment by luisroque** [comment]
That is weird. You can try to add the line below to the Dockerfile. It is not ideal, but it should work.

`RUN python -c "import nltk; nltk.download('punkt')"`
